package alexndr.plugins.SimpleOres;

import java.util.List;

import com.google.common.collect.Lists;

/**
 * @author AleXndrTheGr8st
 */
public class ModInfo {
	public static final String ID = "simpleores";
	public static final String NAME = "SimpleOres 2";
	public static final String VERSION = "@MODVERSION@";
	public static final String DESCRIPTION = "A simple ore plugin for SimpleCore API, featuring 5 unique, balanced ores.";
	public static final String URL = "http://minecraft.curseforge.com/projects/simpleores";
	public static final List<String> AUTHORS = Lists.newArrayList("AleXndrTheGr8st");
	public static final String CREDITS = "Created by AleXndrTheGr8st.";
	public static final String LOGO = "/assets/simplecore/logos/SimpleOres.png";
	public static final String PARENT = "";
	
	public static final boolean USEDEPENDENCYINFO = true;
	public static final String VERSIONURL = "https://raw.githubusercontent.com/Sinhika/SimpleOres2/dev1.8.9/update.json";

//	public static void setModInfoProperties(FMLPreInitializationEvent event) {
//		event.getModMetadata().autogenerated = false;
//		event.getModMetadata().modId = ID;
//		event.getModMetadata().name = NAME;
//		event.getModMetadata().description = DESCRIPTION;
//		event.getModMetadata().version = VERSION;
//		event.getModMetadata().url = URL;
//		event.getModMetadata().authorList = AUTHORS;
//		event.getModMetadata().credits = CREDITS;
//		event.getModMetadata().logoFile = LOGO;
//		event.getModMetadata().parent = PARENT;
//		event.getModMetadata().useDependencyInformation = USEDEPENDENCYINFO;
//	}
}
